### ISSUE TITLE
[Remoto] Fractal - Desenvolvedor iOS

### ISSUE THREAD

**Issue by nielsonrolim** [CocoaHeadsBrasil/vagas#212]
## Empresa
A Fractal Tecnologia é uma empresa que visa contribuir com a melhoria na educação do mundo através do desenvolvimento de ferramentas que facilitam a vida de estudantes e educadores. Nossa filosofia é que através do aprendizado conseguimos nos tornar pessoas melhores e assim contribuir para um mundo melhor, por isso damos incentivo ao auto-desenvolvimento investindo na sua carreira e lhe proporcionando horários flexíveis.
Temos um ambiente de trabalho flexível, moderno, descontraído e colaborativo onde sua opinião é importante para crescermos juntos.
Gosta de trabalhar de bermuda? Vem pra cá! O que importa pra gente é o que você traz de conhecimento para compartilhar e a vontade de aprender.

## Descrição da vaga
Desenvolver aplicativos iOS integrados com APIs RESTful.

## Posição
Desenvolvedor iOS Junior ou Pleno

## Tipo de contratação
Remoto ou presencial em João Pessoa, PB
Pessoa Jurídica ou Autônomo 

###### Obrigatórios
Swift 3
Diretrizes do iOS Human Interface Guidelines
Auto Layout
APIs RESTful
CocoaPods
JSON
Git
SCRUM
SQLite (Realm)

###### Desejáveis
Clean Architecture (VIPER)
XCTests
Desenvolvimento de interfaces NIB ou View Code

###### Diferenciais
React Swift
GraphQL

## Como aplicar
Envie seu currículo para recrutamento@fractaltecnologia.com.br

## Contato
Para mais informações: recrutamento@fractaltecnologia.com.br

**Comment by martinitorquato** [comment]
@Viniciuscarvalho  ainda contratando?

**Comment by Viniciuscarvalho** [comment]
Não sou o responsável pela vaga, acho que seria válido perguntar pro @nielsonrolim 👍

**Comment by nielsonrolim** [comment]
Oi @martinitorquato! Desculpe a demora para responder.

Sim, ainda estamos contratando. Pode enviar seu currículo.

**Comment by martinitorquato** [comment]
Nielson tudo bom?
Poderia me informar seu e-mail para que eu possa estar enviando o CV?

Att. Raphael Martini



On October 17, 2017 at 1:19:06 PM, Nielson Rolim (notifications@github.com)
wrote:

Oi @martinitorquato <https://github.com/martinitorquato>! Desculpe a demora
para responder.

Sim, ainda estamos contratando. Pode enviar seu currículo.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CocoaHeadsBrasil/vagas/issues/212#issuecomment-337263656>,
or mute the thread
